### ISSUE TITLE
Error while waiting for Protractor to sync with the page: "window.angular is undefined.

### ISSUE THREAD

**Issue by anuradhadande** [serenity-js/tutorial-from-scripts-to-serenity#7]
I got this error while executing the feature file add_new_items from tutorial.
Step Definition: features/step_definitions/todo_user.steps.ts:24
   Message:
     Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
         at runWaitForAngularScript.then (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/browser.ts:653:19)
         at ManagedPromise.invokeCallback_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:1366:14)
         at TaskQueue.execute_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2970:14)
         at TaskQueue.executeNext_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2953:27)
         at asyncRun (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:2813:27)
         at /Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/selenium-webdriver/lib/promise.js:676:7
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)Error
         at ElementArrayFinder.applyAction_ (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:482:23)
         at ElementArrayFinder.(anonymous function).args [as sendKeys] (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:96:21)
         at ElementFinder.(anonymous function).args [as sendKeys] (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/protractor/lib/element.ts:873:14)
         at EnterValue.performAs (/Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/serenity-js/src/serenity-protractor/screenplay/interactions/enter.ts:41:59)
         at /Users/anuradhadande/tutorial-from-scripts-to-serenity/node_modules/@serenity-js/core/src/screenplay/actor.ts:112:43
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)

Can you tell me how to fix this?

**Comment by stefanschenk** [comment]
I have this same issue following the tutorial on http://serenity-js.org/from-scripts-to-serenity/writing-what-you-would-like-to-read.html.

When I run the test I can see my browser being opened, but the script does not wait for the page to load. It immediately tries to execute the 'When he adds...' step and thats when the protractor error is thrown.

**Comment by dadakoko** [comment]
checkout the 1-first-scenario-implemented branch, install protractor-cucumber-framework and the scenario passed

**Comment by onadikuda** [comment]
I have same issue now and couldn't find the solution yet. Please help us out.

**Comment by frosted-fern** [comment]
Also having a similar issue. Has there been any solutions?

**Comment by teochengyong** [comment]
having similar issue. I think the demo no longer works.

**Comment by jan-molak** [comment]
It looks like the TodoMVC app has changed the way to identify the input field (instead of a css id it now uses a css class). I've fixed that on branch `2-reports`, so please see if the following works for you:

```
git clone https://github.com/serenity-js/tutorial-from-scripts-to-serenity.git
cd tutorial-from-scripts-to-serenity                                          
git checkout 2-reports
npm install
npm test
```

Having said that, I'm currently working on a new tutorial to support the upcoming release of Serenity/JS version 2 so watch this space :-)

**Comment by jan-molak** [comment]
Hi guys, Serenity/JS 2.0 is now available, so please use one of the new template projects to get started with the framework:
- [`serenity-js-cucumber-protractor-template`](https://github.com/serenity-js/serenity-js-cucumber-protractor-template)
- [`serenity-js-jasmine-protractor-template`](https://github.com/serenity-js/serenity-js-jasmine-protractor-template)

You might be also interested in the [video](https://serenity-js.org/handbook/demo.html) demonstrating some of the new features, as well as the [updated tutorial](https://serenity-js.org/handbook/thinking-in-serenity-js/index.html).
